version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
    volumes:
      # Persistencia de datos en la carpeta local ./mysql
      - ./mysql:/var/lib/mysql
    ports:
      # Mapeamos el puerto 3307 de tu PC al 3306 del contenedor
      # Usamos el 3307 para no chocar si ya tienes un MySQL instalado.
      - "3307:3306"